function [nSec,bPrimBias,bSecBias] = TrfConfigureDlg()

    d = dialog('Position',[300 300 300 150],'Name','Configure your transformer');
    
    txt = uicontrol('Parent',d,...
         'Unit','normalized',...
           'Style','text',...
           'HorizontalAlignment','left',...
           'Position',[0.05 0.8 0.5 0.1],...
           'String','Number of Secondaries');
       
    nSecDrop = uicontrol('Parent',d,...
        'Unit','normalized',...
           'Style','popup',...
           'Position',[0.6 0.8 0.35 0.1],...
           'String',{'1';'2';'3'},...
           'Callback',@popup_callback);
       
    PrimBias = uicontrol('Parent',d,...
        'Unit','normalized',...
           'Style','CheckBox',...
           'Value',false,...
           'Position',[0.05 0.6 0.5 0.1],...
           'String','Include Primary Bias',...
           'Callback',@setPrimBiasFlag);   
       
     SecBias = uicontrol('Parent',d,...
         'Unit','normalized',...
           'Style','CheckBox',...
           'Value',false,...
           'Position',[0.05 0.4 0.5 0.1],...
           'String','Include Secondary Bias',...
           'Callback',@setPrSecBiasFlag);   
       
    btn = uicontrol('Parent',d,...
           'Position',[100 20 70 20],...
           'String','Ok',...
           'Callback','delete(gcf)');
       
   btn = uicontrol('Parent',d,...
       'Position',[190 20 70 20],...
       'String','Close',...
       'Callback','delete(gcf)');
       
    nSec = 1;
    bPrimBias = false;  
    bSecBias = false;
    % Wait for d to close before running to completion
    uiwait(d);
   
    
    
    
       function popup_callback(popup,event)
          idx = popup.Value;
          popup_items = popup.String;
          nSec = str2double(char(popup_items(idx,:)));
       end
   
    function setPrimBiasFlag(src,event)
         bPrimBias = src.Value;
    end

    function setPrSecBiasFlag(src,event)
        bSecBias    = src.Value;
    end
end